use crate::types::{EmojiCategory, KaomojiCategory, SymbolCategory};

pub struct EmojiItem {
    pub char: &'static str,
    pub name: &'static str,
    pub category: EmojiCategory,
}

pub struct SymbolItem {
    pub symbol: &'static str,
    pub name: &'static str,
    pub category: SymbolCategory,
}

pub struct KaomojiItem {
    pub text: &'static str,
    pub category: KaomojiCategory,
}

pub fn get_emojis() -> Vec<EmojiItem> {
    vec![
        // Smileys
        EmojiItem { char: "😀", name: "grinning face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😃", name: "grinning face with big eyes", category: EmojiCategory::Smileys },
        EmojiItem { char: "😄", name: "grinning face with smiling eyes", category: EmojiCategory::Smileys },
        EmojiItem { char: "😁", name: "beaming face with smiling eyes", category: EmojiCategory::Smileys },
        EmojiItem { char: "😆", name: "grinning squinting face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😅", name: "grinning face with sweat", category: EmojiCategory::Smileys },
        EmojiItem { char: "🤣", name: "rolling on the floor laughing", category: EmojiCategory::Smileys },
        EmojiItem { char: "😂", name: "face with tears of joy", category: EmojiCategory::Smileys },
        EmojiItem { char: "🙂", name: "slightly smiling face", category: EmojiCategory::Smileys },
        EmojiItem { char: "🙃", name: "upside down face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😉", name: "winking face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😊", name: "smiling face with smiling eyes", category: EmojiCategory::Smileys },
        EmojiItem { char: "😇", name: "smiling face with halo", category: EmojiCategory::Smileys },
        EmojiItem { char: "🥰", name: "smiling face with hearts", category: EmojiCategory::Smileys },
        EmojiItem { char: "😍", name: "smiling face with heart eyes", category: EmojiCategory::Smileys },
        EmojiItem { char: "🤩", name: "star struck", category: EmojiCategory::Smileys },
        EmojiItem { char: "😘", name: "face blowing a kiss", category: EmojiCategory::Smileys },
        EmojiItem { char: "😗", name: "kissing face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😋", name: "face savoring food", category: EmojiCategory::Smileys },
        EmojiItem { char: "😛", name: "face with tongue", category: EmojiCategory::Smileys },
        EmojiItem { char: "😜", name: "winking face with tongue", category: EmojiCategory::Smileys },
        EmojiItem { char: "🤪", name: "zany face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😝", name: "squinting face with tongue", category: EmojiCategory::Smileys },
        EmojiItem { char: "🤑", name: "money mouth face", category: EmojiCategory::Smileys },
        EmojiItem { char: "🤗", name: "smiling face with open hands", category: EmojiCategory::Smileys },
        EmojiItem { char: "🤭", name: "face with hand over mouth", category: EmojiCategory::Smileys },
        EmojiItem { char: "🤫", name: "shushing face", category: EmojiCategory::Smileys },
        EmojiItem { char: "🤔", name: "thinking face", category: EmojiCategory::Smileys },
        EmojiItem { char: "🤐", name: "zipper mouth face", category: EmojiCategory::Smileys },
        EmojiItem { char: "🤨", name: "face with raised eyebrow", category: EmojiCategory::Smileys },
        EmojiItem { char: "😐", name: "neutral face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😑", name: "expressionless face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😶", name: "face without mouth", category: EmojiCategory::Smileys },
        EmojiItem { char: "😏", name: "smirking face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😒", name: "unamused face", category: EmojiCategory::Smileys },
        EmojiItem { char: "🙄", name: "face with rolling eyes", category: EmojiCategory::Smileys },
        EmojiItem { char: "😬", name: "grimacing face", category: EmojiCategory::Smileys },
        EmojiItem { char: "🤥", name: "lying face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😌", name: "relieved face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😔", name: "pensive face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😪", name: "sleepy face", category: EmojiCategory::Smileys },
        EmojiItem { char: "🤤", name: "drooling face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😴", name: "sleeping face", category: EmojiCategory::Smileys },
        EmojiItem { char: "😷", name: "face with medical mask", category: EmojiCategory::Smileys },
        EmojiItem { char: "😎", name: "smiling face with sunglasses", category: EmojiCategory::Smileys },
        EmojiItem { char: "🤓", name: "nerd face", category: EmojiCategory::Smileys },
        EmojiItem { char: "🧐", name: "face with monocle", category: EmojiCategory::Smileys },

        // Animals
        EmojiItem { char: "🐶", name: "dog face", category: EmojiCategory::Animals },
        EmojiItem { char: "🐱", name: "cat face", category: EmojiCategory::Animals },
        EmojiItem { char: "🐭", name: "mouse face", category: EmojiCategory::Animals },
        EmojiItem { char: "🐹", name: "hamster face", category: EmojiCategory::Animals },
        EmojiItem { char: "🐰", name: "rabbit face", category: EmojiCategory::Animals },
        EmojiItem { char: "🦊", name: "fox", category: EmojiCategory::Animals },
        EmojiItem { char: "🐻", name: "bear", category: EmojiCategory::Animals },
        EmojiItem { char: "🐼", name: "panda", category: EmojiCategory::Animals },
        EmojiItem { char: "🐨", name: "koala", category: EmojiCategory::Animals },
        EmojiItem { char: "🐯", name: "tiger face", category: EmojiCategory::Animals },
        EmojiItem { char: "🦁", name: "lion", category: EmojiCategory::Animals },
        EmojiItem { char: "🐮", name: "cow face", category: EmojiCategory::Animals },
        EmojiItem { char: "🐷", name: "pig face", category: EmojiCategory::Animals },
        EmojiItem { char: "🐸", name: "frog", category: EmojiCategory::Animals },
        EmojiItem { char: "🐵", name: "monkey face", category: EmojiCategory::Animals },
        EmojiItem { char: "🦄", name: "unicorn", category: EmojiCategory::Animals },
        EmojiItem { char: "🐝", name: "honeybee", category: EmojiCategory::Animals },
        EmojiItem { char: "🦋", name: "butterfly", category: EmojiCategory::Animals },

        // Food
        EmojiItem { char: "🍏", name: "green apple", category: EmojiCategory::Food },
        EmojiItem { char: "🍎", name: "red apple", category: EmojiCategory::Food },
        EmojiItem { char: "🍐", name: "pear", category: EmojiCategory::Food },
        EmojiItem { char: "🍊", name: "tangerine", category: EmojiCategory::Food },
        EmojiItem { char: "🍋", name: "lemon", category: EmojiCategory::Food },
        EmojiItem { char: "🍌", name: "banana", category: EmojiCategory::Food },
        EmojiItem { char: "🍉", name: "watermelon", category: EmojiCategory::Food },
        EmojiItem { char: "🍇", name: "grapes", category: EmojiCategory::Food },
        EmojiItem { char: "🍓", name: "strawberry", category: EmojiCategory::Food },
        EmojiItem { char: "🫐", name: "blueberries", category: EmojiCategory::Food },
        EmojiItem { char: "🍒", name: "cherries", category: EmojiCategory::Food },
        EmojiItem { char: "🍑", name: "peach", category: EmojiCategory::Food },
        EmojiItem { char: "🥭", name: "mango", category: EmojiCategory::Food },
        EmojiItem { char: "🍍", name: "pineapple", category: EmojiCategory::Food },
        EmojiItem { char: "🥥", name: "coconut", category: EmojiCategory::Food },
        EmojiItem { char: "🥝", name: "kiwi fruit", category: EmojiCategory::Food },
        EmojiItem { char: "🍅", name: "tomato", category: EmojiCategory::Food },
        EmojiItem { char: "🥑", name: "avocado", category: EmojiCategory::Food },
        EmojiItem { char: "🍆", name: "eggplant", category: EmojiCategory::Food },
        EmojiItem { char: "🍕", name: "pizza", category: EmojiCategory::Food },
        EmojiItem { char: "🍔", name: "hamburger", category: EmojiCategory::Food },
        EmojiItem { char: "🍟", name: "french fries", category: EmojiCategory::Food },
        EmojiItem { char: "🌭", name: "hot dog", category: EmojiCategory::Food },
        EmojiItem { char: "🍿", name: "popcorn", category: EmojiCategory::Food },
        EmojiItem { char: "☕", name: "hot beverage coffee", category: EmojiCategory::Food },
        EmojiItem { char: "🍵", name: "teacup without handle", category: EmojiCategory::Food },
        EmojiItem { char: "🧋", name: "bubble tea", category: EmojiCategory::Food },

        // Activities
        EmojiItem { char: "⚽", name: "soccer ball", category: EmojiCategory::Activities },
        EmojiItem { char: "🏀", name: "basketball", category: EmojiCategory::Activities },
        EmojiItem { char: "🏈", name: "american football", category: EmojiCategory::Activities },
        EmojiItem { char: "⚾", name: "baseball", category: EmojiCategory::Activities },
        EmojiItem { char: "🎾", name: "tennis", category: EmojiCategory::Activities },
        EmojiItem { char: "🏐", name: "volleyball", category: EmojiCategory::Activities },
        EmojiItem { char: "🏉", name: "rugby football", category: EmojiCategory::Activities },
        EmojiItem { char: "🥏", name: "flying disc", category: EmojiCategory::Activities },
        EmojiItem { char: "🎱", name: "pool 8 ball", category: EmojiCategory::Activities },
        EmojiItem { char: "🏓", name: "ping pong", category: EmojiCategory::Activities },
        EmojiItem { char: "🏸", name: "badminton", category: EmojiCategory::Activities },
        EmojiItem { char: "🥊", name: "boxing glove", category: EmojiCategory::Activities },
        EmojiItem { char: "🎯", name: "bullseye dart", category: EmojiCategory::Activities },
        EmojiItem { char: "🎮", name: "video game controller", category: EmojiCategory::Activities },
        EmojiItem { char: "🎨", name: "artist palette", category: EmojiCategory::Activities },
        EmojiItem { char: "🎭", name: "performing arts", category: EmojiCategory::Activities },

        // Travel
        EmojiItem { char: "🚗", name: "automobile car", category: EmojiCategory::Travel },
        EmojiItem { char: "🚕", name: "taxi", category: EmojiCategory::Travel },
        EmojiItem { char: "🚙", name: "sport utility vehicle", category: EmojiCategory::Travel },
        EmojiItem { char: "🚌", name: "bus", category: EmojiCategory::Travel },
        EmojiItem { char: "🏎️", name: "racing car", category: EmojiCategory::Travel },
        EmojiItem { char: "🚓", name: "police car", category: EmojiCategory::Travel },
        EmojiItem { char: "🚑", name: "ambulance", category: EmojiCategory::Travel },
        EmojiItem { char: "🚒", name: "fire engine", category: EmojiCategory::Travel },
        EmojiItem { char: "✈️", name: "airplane", category: EmojiCategory::Travel },
        EmojiItem { char: "🚀", name: "rocket", category: EmojiCategory::Travel },
        EmojiItem { char: "🛸", name: "flying saucer", category: EmojiCategory::Travel },
        EmojiItem { char: "🚁", name: "helicopter", category: EmojiCategory::Travel },
        EmojiItem { char: "⛵", name: "sailboat", category: EmojiCategory::Travel },
        EmojiItem { char: "⚓", name: "anchor", category: EmojiCategory::Travel },

        // Objects
        EmojiItem { char: "⌚", name: "watch", category: EmojiCategory::Objects },
        EmojiItem { char: "📱", name: "mobile phone", category: EmojiCategory::Objects },
        EmojiItem { char: "💻", name: "laptop", category: EmojiCategory::Objects },
        EmojiItem { char: "⌨️", name: "keyboard", category: EmojiCategory::Objects },
        EmojiItem { char: "🖥️", name: "desktop computer", category: EmojiCategory::Objects },
        EmojiItem { char: "🖨️", name: "printer", category: EmojiCategory::Objects },
        EmojiItem { char: "🖱️", name: "computer mouse", category: EmojiCategory::Objects },
        EmojiItem { char: "📷", name: "camera", category: EmojiCategory::Objects },
        EmojiItem { char: "💡", name: "light bulb", category: EmojiCategory::Objects },
        EmojiItem { char: "🔦", name: "flashlight", category: EmojiCategory::Objects },
        EmojiItem { char: "📖", name: "open book", category: EmojiCategory::Objects },
        EmojiItem { char: "✏️", name: "pencil", category: EmojiCategory::Objects },
        EmojiItem { char: "📌", name: "pushpin", category: EmojiCategory::Objects },
        EmojiItem { char: "📎", name: "paperclip", category: EmojiCategory::Objects },
        EmojiItem { char: "🔑", name: "key", category: EmojiCategory::Objects },
        EmojiItem { char: "🔒", name: "locked", category: EmojiCategory::Objects },

        // Symbols
        EmojiItem { char: "❤️", name: "red heart", category: EmojiCategory::Symbols },
        EmojiItem { char: "🧡", name: "orange heart", category: EmojiCategory::Symbols },
        EmojiItem { char: "💛", name: "yellow heart", category: EmojiCategory::Symbols },
        EmojiItem { char: "💚", name: "green heart", category: EmojiCategory::Symbols },
        EmojiItem { char: "💙", name: "blue heart", category: EmojiCategory::Symbols },
        EmojiItem { char: "💜", name: "purple heart", category: EmojiCategory::Symbols },
        EmojiItem { char: "🖤", name: "black heart", category: EmojiCategory::Symbols },
        EmojiItem { char: "🤍", name: "white heart", category: EmojiCategory::Symbols },
        EmojiItem { char: "💯", name: "hundred points", category: EmojiCategory::Symbols },
        EmojiItem { char: "🔥", name: "fire flame", category: EmojiCategory::Symbols },
        EmojiItem { char: "⭐", name: "star", category: EmojiCategory::Symbols },
        EmojiItem { char: "✨", name: "sparkles", category: EmojiCategory::Symbols },
        EmojiItem { char: "⚡", name: "high voltage lightning", category: EmojiCategory::Symbols },
        EmojiItem { char: "✅", name: "check mark button", category: EmojiCategory::Symbols },
        EmojiItem { char: "❌", name: "cross mark", category: EmojiCategory::Symbols },
    ]
}

pub fn get_symbols() -> Vec<SymbolItem> {
    vec![
        // Currency
        SymbolItem { symbol: "$", name: "dollar sign", category: SymbolCategory::Currency },
        SymbolItem { symbol: "€", name: "euro sign", category: SymbolCategory::Currency },
        SymbolItem { symbol: "£", name: "pound sign", category: SymbolCategory::Currency },
        SymbolItem { symbol: "¥", name: "yen sign", category: SymbolCategory::Currency },
        SymbolItem { symbol: "₹", name: "indian rupee sign", category: SymbolCategory::Currency },
        SymbolItem { symbol: "₿", name: "bitcoin sign", category: SymbolCategory::Currency },
        SymbolItem { symbol: "¢", name: "cent sign", category: SymbolCategory::Currency },
        SymbolItem { symbol: "₩", name: "won sign", category: SymbolCategory::Currency },
        SymbolItem { symbol: "₺", name: "turkish lira sign", category: SymbolCategory::Currency },
        SymbolItem { symbol: "₴", name: "hryvnia sign", category: SymbolCategory::Currency },
        SymbolItem { symbol: "₱", name: "peso sign", category: SymbolCategory::Currency },

        // Math
        SymbolItem { symbol: "±", name: "plus minus", category: SymbolCategory::Math },
        SymbolItem { symbol: "≠", name: "not equal to", category: SymbolCategory::Math },
        SymbolItem { symbol: "≈", name: "almost equal to", category: SymbolCategory::Math },
        SymbolItem { symbol: "≤", name: "less than or equal to", category: SymbolCategory::Math },
        SymbolItem { symbol: "≥", name: "greater than or equal to", category: SymbolCategory::Math },
        SymbolItem { symbol: "÷", name: "division sign", category: SymbolCategory::Math },
        SymbolItem { symbol: "×", name: "multiplication sign", category: SymbolCategory::Math },
        SymbolItem { symbol: "√", name: "square root", category: SymbolCategory::Math },
        SymbolItem { symbol: "∞", name: "infinity", category: SymbolCategory::Math },
        SymbolItem { symbol: "π", name: "pi", category: SymbolCategory::Math },
        SymbolItem { symbol: "∑", name: "n-ary summation", category: SymbolCategory::Math },
        SymbolItem { symbol: "∫", name: "integral", category: SymbolCategory::Math },
        SymbolItem { symbol: "∆", name: "increment delta", category: SymbolCategory::Math },
        SymbolItem { symbol: "∂", name: "partial differential", category: SymbolCategory::Math },
        SymbolItem { symbol: "‰", name: "per mille sign", category: SymbolCategory::Math },

        // Punctuation & Marks
        SymbolItem { symbol: "—", name: "em dash", category: SymbolCategory::Punctuation },
        SymbolItem { symbol: "–", name: "en dash", category: SymbolCategory::Punctuation },
        SymbolItem { symbol: "•", name: "bullet point", category: SymbolCategory::Punctuation },
        SymbolItem { symbol: "…", name: "horizontal ellipsis", category: SymbolCategory::Punctuation },
        SymbolItem { symbol: "©", name: "copyright sign", category: SymbolCategory::Punctuation },
        SymbolItem { symbol: "®", name: "registered sign", category: SymbolCategory::Punctuation },
        SymbolItem { symbol: "™", name: "trade mark sign", category: SymbolCategory::Punctuation },
        SymbolItem { symbol: "°", name: "degree sign", category: SymbolCategory::Punctuation },
        SymbolItem { symbol: "†", name: "dagger", category: SymbolCategory::Punctuation },
        SymbolItem { symbol: "‡", name: "double dagger", category: SymbolCategory::Punctuation },
        SymbolItem { symbol: "¶", name: "pilcrow paragraph sign", category: SymbolCategory::Punctuation },
        SymbolItem { symbol: "§", name: "section sign", category: SymbolCategory::Punctuation },

        // Arrows
        SymbolItem { symbol: "←", name: "leftwards arrow", category: SymbolCategory::Arrows },
        SymbolItem { symbol: "→", name: "rightwards arrow", category: SymbolCategory::Arrows },
        SymbolItem { symbol: "↑", name: "upwards arrow", category: SymbolCategory::Arrows },
        SymbolItem { symbol: "↓", name: "downwards arrow", category: SymbolCategory::Arrows },
        SymbolItem { symbol: "↔", name: "left right arrow", category: SymbolCategory::Arrows },
        SymbolItem { symbol: "↕", name: "up down arrow", category: SymbolCategory::Arrows },
        SymbolItem { symbol: "↖", name: "north west arrow", category: SymbolCategory::Arrows },
        SymbolItem { symbol: "↗", name: "north east arrow", category: SymbolCategory::Arrows },
        SymbolItem { symbol: "↘", name: "south east arrow", category: SymbolCategory::Arrows },
        SymbolItem { symbol: "↙", name: "south west arrow", category: SymbolCategory::Arrows },
        SymbolItem { symbol: "⇄", name: "rightwards arrow over leftwards arrow", category: SymbolCategory::Arrows },

        // Greek
        SymbolItem { symbol: "α", name: "alpha", category: SymbolCategory::Greek },
        SymbolItem { symbol: "β", name: "beta", category: SymbolCategory::Greek },
        SymbolItem { symbol: "γ", name: "gamma", category: SymbolCategory::Greek },
        SymbolItem { symbol: "δ", name: "delta", category: SymbolCategory::Greek },
        SymbolItem { symbol: "ε", name: "epsilon", category: SymbolCategory::Greek },
        SymbolItem { symbol: "θ", name: "theta", category: SymbolCategory::Greek },
        SymbolItem { symbol: "λ", name: "lambda", category: SymbolCategory::Greek },
        SymbolItem { symbol: "μ", name: "mu", category: SymbolCategory::Greek },
        SymbolItem { symbol: "σ", name: "sigma", category: SymbolCategory::Greek },
        SymbolItem { symbol: "τ", name: "tau", category: SymbolCategory::Greek },
        SymbolItem { symbol: "φ", name: "phi", category: SymbolCategory::Greek },
        SymbolItem { symbol: "ω", name: "omega", category: SymbolCategory::Greek },
    ]
}

pub fn get_kaomojis() -> Vec<KaomojiItem> {
    vec![
        // Happy
        KaomojiItem { text: "(⁠◕⁠ᴗ⁠◕⁠✿⁠)", category: KaomojiCategory::Happy },
        KaomojiItem { text: "(⁠•⁠‿⁠•⁠)", category: KaomojiCategory::Happy },
        KaomojiItem { text: "(⁠~⁠￣⁠³⁠￣⁠)⁠~", category: KaomojiCategory::Happy },
        KaomojiItem { text: "(⁠◍⁠•⁠ᴗ⁠•⁠◍⁠)", category: KaomojiCategory::Happy },
        KaomojiItem { text: "\\(⁠^⁠o⁠^⁠)/", category: KaomojiCategory::Happy },
        KaomojiItem { text: "(⁠≧⁠▽⁠≦⁠)", category: KaomojiCategory::Happy },

        // Shrug
        KaomojiItem { text: "¯\\_(ツ)_/¯", category: KaomojiCategory::Shrug },
        KaomojiItem { text: "┐(´∀｀)┌", category: KaomojiCategory::Shrug },
        KaomojiItem { text: "┐(‘～`;)┌", category: KaomojiCategory::Shrug },
        KaomojiItem { text: "╮(─▽─)╭", category: KaomojiCategory::Shrug },

        // Angry
        KaomojiItem { text: "(╯°□°）╯︵ ┻━┻", category: KaomojiCategory::Angry },
        KaomojiItem { text: "(╬▔皿▔)╯", category: KaomojiCategory::Angry },
        KaomojiItem { text: "┬─┬ノ( º _ ºノ)", category: KaomojiCategory::Angry },
        KaomojiItem { text: "(ಠ_ಠ)", category: KaomojiCategory::Angry },

        // Surprised
        KaomojiItem { text: "(⁠⊙⁠_⁠⊙⁠)", category: KaomojiCategory::Surprised },
        KaomojiItem { text: "(⁠O⁠_⁠o⁠)", category: KaomojiCategory::Surprised },
        KaomojiItem { text: "Σ(°Location°)", category: KaomojiCategory::Surprised },
        KaomojiItem { text: "(⁠゜⁠o⁠゜⁠)", category: KaomojiCategory::Surprised },

        // Sad
        KaomojiItem { text: "(╥﹏╥)", category: KaomojiCategory::Sad },
        KaomojiItem { text: "(⁠༎ຶ⁠‿⁠༎ຶ⁠)", category: KaomojiCategory::Sad },
        KaomojiItem { text: "(⁠p⁠_⁠q⁠)", category: KaomojiCategory::Sad },
        KaomojiItem { text: "(⁠〒⁠﹏⁠〒⁠)", category: KaomojiCategory::Sad },

        // Love
        KaomojiItem { text: "(⁠*⁠˘⁠︶⁠˘⁠*⁠)⁠.⁠｡⁠*⁠♡", category: KaomojiCategory::Love },
        KaomojiItem { text: "(⁠｡⁠・⁠//⁠ε⁠//⁠・⁠｡⁠)", category: KaomojiCategory::Love },
        KaomojiItem { text: "(⁠♡⁠ω⁠♡⁠)⁠~⁠♪", category: KaomojiCategory::Love },
        KaomojiItem { text: "(*￣3￣)╭", category: KaomojiCategory::Love },
    ]
}
